name: 'Create PR from upstream repos for private forks'
description: 'Create PR from upstream repos for private forks'
author: '@himadrisingh'
inputs:
  upstream:
    description: 'Upstream repo'
    required: true
  upstream_branch:
    description: 'Upstream branch to pull from'
    required: true
  branch:
    description: 'Branch to merge to'
    required: true
  pr_labels:
    description: 'Labels for the new PR'
    required: false
    default: 'autocreated'
  pr_title:
    description: 'Title for the PRs opened'
    required: false
    default: 'Upstream'
  sync_branch_prefix:
    description: 'Prefix to be used for sync branches'
    required: false
    default: 'up'
  denoise_message:
    description: 'In case source is inside the same repo - the GHA runs of the opened PR may pollute the original commit-s status. Setting this enables a try to auto-merge the base branch - but if unsuccessfull falls back to add a technical commit commit message with the given message'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: git-merge
  color: yellow
